config/routes.rb
Rails.application.routes.draw do
root "events#index"
get "events" => "events#index"
get "events/:id" => "events#show", as: "event"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  def free?
    # price == 0
    # above is original. below is improvement
    # if either conditon is met, the price will be zero
    # decided as a default, if price is blank, we'll assume price is free
    price.blank? || price.zero?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def format_price(event)
    # if event.price == 0
    # EventsHelper is a view helper
    # price setting is actually a buiness deciscion and would be better off in the model
    # we can take the ".price == 0" portion above and replace it with ".free?"
    # ".free?" is defined in the model
    if event.free?
      # "<strong>Free!</strong>".html_safe
      # OR...
      content_tag :strong, "Free!"
    else
      number_to_currency(event.price)
    end
  end
end

app/views/events/index.html.erb
<h1><%= pluralize @events.length, "Event" %></h1>

  <% @events.each do |event| %>
    <article class="">
      <header>
        <!-- <h2><%= link_to event.name,  event_path(id: event.id)%></h2> -->
        <!-- OR... -->
        <!-- rails is built that you can just pass the object and it will automatially extract the id -->
        <!-- <h2><%= link_to event.name,  event_path(event)%></h2> -->
        <!-- OR... -->
        <!-- rails has a shortcut where we can just pass the event object and will automatially generate the correct helper path -->
        <h2><%= link_to event.name, event %></h2>
      </header>
      <p>
        <%= truncate event.description, length: 25, separator: " " %>
      </p>
      <table>
        <tr>
          <th>When:</th>
          <td><%= event.starts_at %></td>
        </tr>
        <tr>
          <th>Where:</th>
          <td><%= event.location %></td>
        </tr>
        <tr>
          <th>Price:</th>
          <!-- using given rails helper method -->
          <!-- <td><%= number_to_currency event.price %></td> -->
          <!-- using custom helper method -->
          <td><%= format_price event %></td>
        </tr>
      </table>
    </article>
  <% end %>

app/views/events/show.html.erb
<article>
  <header>
    <h1><%= @event.name %></h1>
  </header>
  <p>
    <%= @event.description %>
  </p>
  <h3>When</h3>
  <p>
    <%= @event.starts_at %>
  </p>
  <h3>Where</h3>
  <p>
    <%= @event.location %>
  </p>
  <h3>Price</h3>
  <p>
    <%= format_price @event %>
  </p>
</article>

<%= link_to "All Events", events_path %>
<!-- could also use "root_path" -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>